### ISSUE TITLE
 🪲 BUG! TablePreview is throwing an error in the browser terminal

### ISSUE THREAD

**Issue by eduardo-vargas** [evargast/signature-generator#45]
Please investigate, debug and fix! 😄 

<img width="557" alt="image" src="https://user-images.githubusercontent.com/52969178/232643112-83386f14-bc32-4570-beb8-03e7a0249e10.png">

**Comment by ramirezStefano** [comment]
Hello hello, I see there's a bug. Exterminator Steve will take care of it!
