### ISSUE TITLE
[Stefano] Complete software development certification

### ISSUE THREAD

**Issue by eduardo-vargas** [evargast/signature-generator#66]
What a journey it’s been! This ticket involves a test at the end - take notes and ask questions as you go.

May the odds be ever in your favor 🍻

[Software development certification ](https://www.linkedin.com/learning/paths/career-essentials-in-software-development-by-microsoft-and-linkedin?u=26886434)

**Comment by ramirezStefano** [comment]
Is done!
![](https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExZWQwZTYyNmY0MTZmMDU5ODFmYmQxYWE0MmJiODYwYjRiNzg0ZjhhNSZlcD12MV9pbnRlcm5hbF9naWZzX2dpZklkJmN0PWc/3oKIPf3C7HqqYBVcCk/giphy.gif)
